### PR TITLE
Added Event Sourcing - uses SQL database for now

### PR DESCRIPTION
**Pull request by battermann**
// @CarstenKoenig

### CODE REVIEW

**Comment by CarstenKoenig** [comment]
I have to take a closer look but why did you write the serialization boiler-plate? I think JSON.net is able to [handle union-cases](https://github.com/JamesNK/Newtonsoft.Json/blob/6965fcfa46ee009826ea7f9f5a96150edecca71f/Src/Newtonsoft.Json/Converters/DiscriminatedUnionConverter.cs) fine now (at least I had no issues recently)

**Comment by CarstenKoenig** [comment]
aside from that if you want to have more control (or be quicker) [FsPickler](https://github.com/nessos/FsPickler) might be an option - but this too means some boiler-plate to write

**Comment by battermann** [comment]
I borrowed the serialization from Jérémie Chassaing from [here](https://github.com/thinkbeforecoding/FsUno.Prod/blob/master/FsUno.Persistence.EventStore/Serialization.fs). In his [talk](https://vimeo.com/131632601) he claims that it works better for F# types than just the Newtonsoft.Json serializer. I didn't bother with the details and it works fine for the most part (aside from one issue I had with union cases indeed). But FsPickler looks interesting, too.

**Comment by CarstenKoenig** [comment]
the _boiler-plate_ code you mentioned is the way you handle the only aggregate right inside the `IItemsEventStore` right (you have to copy&paste this basically everyhwere) - you can make this really generic using interfaces because interface-members (just like class members) can be generic (no generic parameter on the interface but still the members have generic parameters) - using this you can get quite far: ([I blogged about this a while ago](http://gettingsharper.de/2015/02/12/functional-event-sourcing-lets-playback-with-fun/))

**Comment by battermann** [comment]
Very interesting article!

Making the event store generic is an important issue, I agree. Besides that, do you think the overall design concerning the event store is reasonable and feasible?

**Comment by battermann** [comment]
Meinst du, dass das Design abgesehen von dem generischen Event Store so in
etwa "production ready" ist?

Oder gibt es da noch unkalkulierbare Risiken?

Ich würde das wahnsinnig gerne so umsetzen, bin mir aber nicht sicher, was
das noch langfristig für Implikationen haben wird / kann?

Grüße
Leif

2015-09-21 15:13 GMT+02:00 Carsten König <notifications@github.com>:

> the *boiler-plate* code you mentioned is the way you handle the only
> aggregate right inside the IItemsEventStore right (you have to copy&paste
> this basically everyhwere) - you can make this really generic using
> interfaces because interface-members (just like class members) can be
> generic (no generic parameter on the interface but still the members have
> generic parameters) - using this you can get quite far: (I blogged about
> this a while ago
> <http://gettingsharper.de/2015/02/12/functional-event-sourcing-lets-playback-with-fun/>
> )
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/battermann/ProjectScaffold/pull/2#issuecomment-141970134>
> .
>



-- 
Leif Battermann | Neusser Str. 718e | 50737 Köln | Mobil: 01573 8151460

**Comment by CarstenKoenig** [comment]
Ich denke schon, das schöne am Eventstore ist ja, dass es eigentlich
keine Riskiken (Datenverlust) gibt - selbst wenn was schief geht und
irgendwelche Readmodels *schief laufen* kann man alles aus den
Ereignissen wieder "abspielen", und solange die Events in JSON (also
nicht gerade mit dem BinarySerializer) gespeichert werden ist das schon
ziemlich sicher.

Aber garantieren kann ich natürlich gar nichts ;)

Gruß,
Carsten


Am 22.09.2015 um 17:10 schrieb Leif Battermann:

**Pull request merged**
