### PR TITLE
- fixed some doc in Models.fs

### PR DESCRIPTION
**Pull request by CarstenKoenig**
mostly my proposed changes to ItemRepository - refactored commonly used stuff into private functions

### CODE REVIEW

**Comment by CarstenKoenig** [comment]
btw: I like the design - maybe the message-bus is in need of some error-handling (it surely is a good place to log stuff) but you could easily extent this and attach an event-store IMO

**Comment by battermann** [comment]
Thanks for submitting the changes! Looks good :)

When an Event Store is added, there is probably no need for logging anymore. Otherwise I would say logging should be done within their own event handlers (that should be registered with the Message Bus). But I would not directly change the Message Bus to do logging, because the Message Bus should not have any knowledge of the domain.

**Comment by CarstenKoenig** [comment]
hey whatever you like ;)

---

The problem I was thinking about is what happens if one (or more handler) raises exceptions - right now it's not deterministic in those cases but from a design perspective you are probably right: it should not matter (although it will in production ... at least in my experience)

**Comment by battermann** [comment]
That's a good point.

But even logging from within the Message Bus can fail^^

**Pull request merged**
